
const SIGMA=5.670374419e-8;
const P={luminosity:1,solarFlux:917,deathRate:.3,heatTransport:20,fertile:1,groundAlbedo:.5,blackAlbedo:.25,whiteAlbedo:.75};
let state={black:.01,white:.01}, speed=1, simTime=0, autoSweep=false, sweepDirection=1;
let history=[], lastSample=0, chartMode="time", responseCache=null, responseDirty=true;
function growth(t){return Math.max(0,1-.003265*(22.5-t)**2)}
function snapshot(s,p=P){const ground=Math.max(0,1-s.black-s.white),open=Math.max(0,p.fertile-s.black-s.white);const albedo=ground*p.groundAlbedo+s.black*p.blackAlbedo+s.white*p.whiteAlbedo;const planetTemp=((p.solarFlux*p.luminosity*(1-albedo))/SIGMA)**.25-273;const blackTemp=planetTemp+p.heatTransport*(albedo-p.blackAlbedo);const whiteTemp=planetTemp+p.heatTransport*(albedo-p.whiteAlbedo);return{ground,open,albedo,planetTemp,blackTemp,whiteTemp,betaB:growth(blackTemp),betaW:growth(whiteTemp)}}
function deriv(s){const z=snapshot(s);return{black:s.black*(z.open*z.betaB-P.deathRate),white:s.white*(z.open*z.betaW-P.deathRate)}}
function add(s,k,m){return{black:s.black+k.black*m,white:s.white+k.white*m}}
function integrate(dt){const k1=deriv(state),k2=deriv(add(state,k1,dt/2)),k3=deriv(add(state,k2,dt/2)),k4=deriv(add(state,k3,dt));state.black+=dt*(k1.black+2*k2.black+2*k3.black+k4.black)/6;state.white+=dt*(k1.white+2*k2.white+2*k3.white+k4.white)/6;state.black=Math.max(1e-7,state.black);state.white=Math.max(1e-7,state.white);const total=state.black+state.white;if(total>P.fertile){state.black*=P.fertile/total;state.white*=P.fertile/total}simTime+=dt}
function lifelessTemp(){return ((P.solarFlux*P.luminosity*(1-P.groundAlbedo))/SIGMA)**.25-273}
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function bindRange(id,out,fmt,key){const el=$(id);el.addEventListener('input',()=>{P[key]=+el.value;$(out).textContent=fmt(+el.value);if(key==='luminosity'){autoSweep=false}});}
bindRange('#luminosity','#lumOut',v=>v.toFixed(2)+' L☉','luminosity');bindRange('#death','#deathOut',v=>v.toFixed(2),'deathRate');bindRange('#transport','#transportOut',v=>v.toFixed(0)+'°C','heatTransport');bindRange('#fertile','#fertileOut',v=>Math.round(v*100)+'%','fertile');
['#death','#transport','#fertile'].forEach(id=>$(id).addEventListener('input',()=>{responseDirty=true}));
$('#speed').addEventListener('input',e=>{speed=+e.target.value;$('#speedOut').textContent=speed.toFixed(1)+'×'});
function setZoom(v){v=Math.max(.70,Math.min(1.80,+v));$('#zoom').value=v;$('#zoomVertical').value=v;$('#zoomOut').textContent=v.toFixed(1)+'×';labWorld?.setZoom(v)}
$('#zoom').addEventListener('input',e=>setZoom(e.target.value));$('#zoomVertical').addEventListener('input',e=>setZoom(e.target.value));$('#zoomReset').onclick=()=>setZoom(1);$('#labCanvas').addEventListener('wheel',e=>{e.preventDefault();setZoom(+$ ('#zoom').value-e.deltaY*.001)},{passive:false});
function reset(){state={black:.01,white:.01};simTime=0;history=[];lastSample=0}$('#resetBtn').onclick=reset;$('#sweepBtn').onclick=()=>{autoSweep=!autoSweep;$('#sweepBtn').textContent=autoSweep?'Stop sweep':'Auto sweep';$('#sweepBtn').classList.toggle('primary',!autoSweep)};
$$('.preset').forEach(b=>b.onclick=()=>{$$('.preset').forEach(x=>x.classList.remove('active'));b.classList.add('active');const v={cold:.72,balanced:1,hot:1.42}[b.dataset.preset];P.luminosity=v;responseDirty=true;$('#luminosity').value=v;$('#lumOut').textContent=v.toFixed(2)+' L☉';reset()});
$('#scienceBtn').onclick=()=>$('#eqDrawer').classList.add('open');$('#eqClose').onclick=()=>$('#eqDrawer').classList.remove('open');
$('#presentBtn').onclick=()=>{document.body.classList.toggle('presenter');if(document.body.classList.contains('presenter'))document.documentElement.requestFullscreen?.();else document.exitFullscreen?.()};document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='p')$('#presentBtn').click()});
function seededFlowers(seed,count){let v=seed>>>0,arr=[];const rnd=()=>((v=(1664525*v+1013904223)>>>0)/4294967296);for(let i=0;i<count;i++)arr.push({x:rnd(),y:rnd(),r:2.2+rnd()*4.8,rot:rnd()*Math.PI*2});return arr}
function makeDaisyTexture(){const c=document.createElement('canvas');c.width=c.height=1024;const x=c.getContext('2d'),MAX=760,blackSeeds=seededFlowers(1983,MAX),whiteSeeds=seededFlowers(284289,MAX);let lastB=-1,lastW=-1;const flower=(f,dark)=>{const px=f.x*1024,py=f.y*1024,r=f.r;x.fillStyle=dark?'#25231e':'#f4efe2';for(let j=0;j<6;j++){const a=f.rot+j*Math.PI/3;x.beginPath();x.ellipse(px+Math.cos(a)*r,py+Math.sin(a)*r,r*.44,r,a,0,Math.PI*2);x.fill()}x.fillStyle=dark?'#d39a32':'#e6ad3c';x.beginPath();x.arc(px,py,r*.55,0,Math.PI*2);x.fill()};const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;tex.updateDaisies=(b,w)=>{const nb=Math.max(0,Math.min(MAX,Math.round(MAX*b))),nw=Math.max(0,Math.min(MAX,Math.round(MAX*w)));if(nb===lastB&&nw===lastW)return;lastB=nb;lastW=nw;const g=x.createLinearGradient(0,0,1024,1024);g.addColorStop(0,'#34452f');g.addColorStop(.55,'#4b5e3e');g.addColorStop(1,'#293b2d');x.fillStyle=g;x.fillRect(0,0,1024,1024);x.globalAlpha=.15;x.fillStyle='#c1c99a';for(let i=0;i<180;i++){const f=blackSeeds[(i*17)%MAX];x.beginPath();x.arc(f.x*1024,f.y*1024,1+f.r*.35,0,Math.PI*2);x.fill()}x.globalAlpha=1;for(let i=0;i<nb;i++)flower(blackSeeds[i],true);for(let i=0;i<nw;i++)flower(whiteSeeds[i],false);tex.needsUpdate=true};tex.updateDaisies(.01,.01);return tex}
function buildPlanet(canvas,hero=false){const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(32,1,.1,100),baseDistance=hero?6.2:5.4;camera.position.set(0,0,baseDistance);const group=new THREE.Group();scene.add(group);const tex=makeDaisyTexture();tex.colorSpace=THREE.SRGBColorSpace;const mat=new THREE.MeshStandardMaterial({map:tex,roughness:.82,metalness:0});const globe=new THREE.Mesh(new THREE.SphereGeometry(1.55,96,96),mat);group.add(globe);const atmos=new THREE.Mesh(new THREE.SphereGeometry(1.59,64,64),new THREE.MeshBasicMaterial({color:0x9ddea0,transparent:true,opacity:.08,side:THREE.BackSide}));group.add(atmos);const ringMat=new THREE.MeshBasicMaterial({color:0xa5d66f,transparent:true,opacity:.36});const ring=new THREE.Mesh(new THREE.TorusGeometry(2.02,.009,8,180),ringMat);ring.rotation.x=1.15;group.add(ring);const sun=new THREE.DirectionalLight(0xffd28a,3);sun.position.set(-4,2,4);scene.add(sun);scene.add(new THREE.HemisphereLight(0xb9e8ff,0x1c130b,1.05));const resize=()=>{const p=canvas.parentElement,w=p.clientWidth,h=p.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()};resize();new ResizeObserver(resize).observe(canvas.parentElement);return{renderer,scene,camera,group,globe,mat,tex,setZoom(v){camera.position.z=baseDistance/v},render(t,z){group.rotation.y+=hero?.0015:.0025;group.rotation.x=Math.sin(t*.0002)*.05;const b=state.black,w=state.white,cover=b+w;tex.updateDaisies(b,w);const warmth=z?.planetTemp??snapshot(state).planetTemp,collapsed=cover<.001,stressed=warmth<8||warmth>37||cover<.08;ringMat.color.set(collapsed?0xef715e:stressed?0xf2b84b:0xa5d66f);ringMat.opacity=collapsed?.48:Math.min(.72,.14+cover*.78);ring.scale.setScalar(1+Math.sin(t*.003)*(.004+Math.min(.012,cover*.018)));mat.color.setHSL(.24-Math.max(-.04,Math.min(.05,(warmth-22)/400)),.28+Math.min(.25,(b+w)*.3),.3+Math.min(.22,w*.35));mat.emissive.set(warmth>35?0x3b1006:warmth<5?0x071a2c:0x071008);mat.emissiveIntensity=.35;renderer.render(scene,camera)}}}
const heroWorld=buildPlanet($('#heroCanvas'),true),labWorld=buildPlanet($('#labCanvas'));
function sizeCanvas(c){const dpr=Math.min(devicePixelRatio,2),r=c.getBoundingClientRect();if(!r.width||!r.height)return null;if(c.width!==Math.round(r.width*dpr)||c.height!==Math.round(r.height*dpr)){c.width=Math.round(r.width*dpr);c.height=Math.round(r.height*dpr)}const x=c.getContext('2d');x.setTransform(dpr,0,0,dpr,0,0);x.clearRect(0,0,r.width,r.height);return{x,r}}
function drawChart(){if(chartMode!=="time")return;const c=$('#chart'),s=sizeCanvas(c);if(!s)return;const{x,r}=s,pad={l:38,r:39,t:11,b:25},w=r.width-pad.l-pad.r,h=r.height-pad.t-pad.b;x.strokeStyle='#ffffff12';x.fillStyle='#777b74';x.font='9px DM Mono';for(let t=-20;t<=60;t+=20){const y=pad.t+h-(t+20)/80*h;x.beginPath();x.moveTo(pad.l,y);x.lineTo(r.width-pad.r,y);x.stroke();x.fillText(t+'°C',2,y+3)}for(let p=0;p<=100;p+=25){const y=pad.t+h-p/100*h;x.fillStyle='#b98b3d';x.fillText(p+'%',r.width-31,y+3)}x.fillStyle='#777b74';x.fillText('model time →',pad.l,pad.t+h+19);if(history.length<2)return;const draw=(key,color,dash=[],right=false)=>{x.strokeStyle=color;x.lineWidth=1.8;x.setLineDash(dash);x.beginPath();history.forEach((d,i)=>{const px=pad.l+i/(Math.max(119,history.length-1))*w,val=d[key],py=right?pad.t+h-val/100*h:pad.t+h-(val+20)/80*h;i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke();x.setLineDash([])};draw('dead','#777',[4,4]);draw('live','#a5d66f');draw('cover','#f2b84b',[],true)}
function equilibriumSweep(reverse=false){const points=[],Ls=Array.from({length:61},(_,i)=>.6+i/60);if(reverse)Ls.reverse();let b=.01,w=.01;for(const L of Ls){if(b+w<1e-5){b=.01;w=.01}for(let n=0;n<5000;n++){const oldL=P.luminosity;P.luminosity=L;const z=snapshot({black:b,white:w});P.luminosity=oldL;b=Math.max(1e-8,b+.035*b*(z.open*z.betaB-P.deathRate));w=Math.max(1e-8,w+.035*w*(z.open*z.betaW-P.deathRate));const total=b+w;if(total>P.fertile){b*=P.fertile/total;w*=P.fertile/total}}const oldL=P.luminosity;P.luminosity=L;const z=snapshot({black:b,white:w});P.luminosity=oldL;points.push({L,temp:z.planetTemp,cover:100*(b+w),dead:((P.solarFlux*L*(1-P.groundAlbedo))/SIGMA)**.25-273})}return reverse?points.reverse():points}
function responseData(){if(responseDirty||!responseCache){responseCache={up:equilibriumSweep(false),down:equilibriumSweep(true)};responseDirty=false}return responseCache}
function drawResponse(){if(chartMode!=="response")return;const c=$('#responseChart'),s=sizeCanvas(c);if(!s)return;const{x,r}=s,pad={l:38,r:39,t:11,b:26},w=r.width-pad.l-pad.r,h=r.height-pad.t-pad.b,d=responseData(),tx=L=>pad.l+(L-.6)*w,ty=t=>pad.t+h-(t+20)/90*h,cy=v=>pad.t+h-v/100*h;x.fillStyle='#ef715e12';let zones=[],start=null;d.up.forEach((q,i)=>{if(q.cover<.1&&start===null)start=i;if(q.cover>=.1&&start!==null){zones.push([start,i-1]);start=null}});if(start!==null)zones.push([start,d.up.length-1]);zones.forEach(([a,b])=>x.fillRect(tx(d.up[a].L),pad.t,Math.max(3,tx(d.up[b].L)-tx(d.up[a].L)),h));x.strokeStyle='#ffffff12';x.font='9px DM Mono';for(let t=-20;t<=70;t+=30){const y=ty(t);x.beginPath();x.moveTo(pad.l,y);x.lineTo(r.width-pad.r,y);x.stroke();x.fillStyle='#777b74';x.fillText(t+'°C',2,y+3)}for(let p=0;p<=100;p+=25){x.fillStyle='#b98b3d';x.fillText(p+'%',r.width-31,cy(p)+3)}const line=(arr,key,color,dash=[],right=false)=>{x.strokeStyle=color;x.lineWidth=1.8;x.setLineDash(dash);x.beginPath();arr.forEach((q,i)=>{const px=tx(q.L),py=right?cy(q[key]):ty(q[key]);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke();x.setLineDash([])};line(d.up,'dead','#666',[4,4]);line(d.up,'temp','#a5d66f');line(d.down,'temp','#a5d66f99',[2,4]);line(d.up,'cover','#f2b84b',[],true);const mx=tx(P.luminosity);x.strokeStyle='#f3eedf';x.lineWidth=1;x.beginPath();x.moveTo(mx,pad.t);x.lineTo(mx,pad.t+h);x.stroke();x.fillStyle='#f3eedf';x.fillText('YOU',Math.min(mx+4,r.width-60),pad.t+10);x.fillStyle='#777b74';for(const L of [.6,.8,1,1.2,1.4,1.6])x.fillText(L.toFixed(1),tx(L)-7,pad.t+h+18);x.fillText('stellar luminosity, L/L₀ →',pad.l,pad.t+h+24)}
$$('.chart-tab').forEach(b=>b.onclick=()=>{$$('.chart-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');chartMode=b.dataset.chart;$('#chart').classList.toggle('hidden',chartMode!=="time");$('#responseChart').classList.toggle('hidden',chartMode!=="response");$('#chartTitle').textContent=chartMode==='time'?'Response through simulated time':'Nonlinear equilibrium + collapse map';$('#chartNote').textContent=chartMode==='time'?'x: model time (arbitrary units) · left: temperature (°C) · right: living cover (%)':'x: stellar luminosity (L/L₀) · left: equilibrium temperature (°C) · right: daisy cover (%)';setTimeout(()=>{drawChart();drawResponse()},10)});
function equilibriumAtCurrentLuminosity(){const curve=responseData().up;return curve.reduce((nearest,point)=>Math.abs(point.L-P.luminosity)<Math.abs(nearest.L-P.luminosity)?point:nearest)}
function updateUI(z){const equilibrium=equilibriumAtCurrentLuminosity();$('#tempValue').textContent=z.planetTemp.toFixed(1)+'°C';$('#equilibriumValue').textContent=equilibrium.temp.toFixed(1)+'°C';$('#albedoValue').textContent=z.albedo.toFixed(2);$('#blackValue').textContent=Math.round(state.black*100)+'%';$('#whiteValue').textContent=Math.round(state.white*100)+'%';$('#groundValue').textContent=Math.round(z.ground*100)+'%';const viable=state.black+state.white>.001;$('#statusText').textContent=!viable?'BIOSPHERE COLLAPSED':Math.abs(z.planetTemp-22.5)<5?'BIOLOGICAL BUFFER ACTIVE':z.planetTemp<5||z.planetTemp>40?'OUTSIDE GROWTH WINDOW':'ECOLOGY ADAPTING';$('#statusText').style.color=viable?'var(--green)':'var(--coral)';const badge=$('#regimeBadge'),cover=state.black+state.white;if(cover<.001){badge.textContent='◆ Regulatory collapse';badge.className='regime-badge collapsed'}else if(z.planetTemp<8||z.planetTemp>37||cover<.08){badge.textContent='▲ Near ecological threshold';badge.className='regime-badge stressed'}else{badge.textContent='● Regulation active';badge.className='regime-badge stable'}$('#heroTemp').textContent=equilibrium.temp.toFixed(1)+'°'}
let last=performance.now();function loop(now){const frame=Math.min(.05,(now-last)/1000);last=now;if(autoSweep){P.luminosity+=sweepDirection*frame*.055;if(P.luminosity>=1.55||P.luminosity<=.65)sweepDirection*=-1;$('#luminosity').value=P.luminosity;$('#lumOut').textContent=P.luminosity.toFixed(2)+' L☉'}const n=Math.ceil(speed*4);for(let i=0;i<n;i++)integrate(frame*speed*2/Math.max(1,n));const z=snapshot(state);if(simTime-lastSample>.35){history.push({live:z.planetTemp,dead:lifelessTemp(),cover:100*(state.black+state.white)});if(history.length>120)history.shift();lastSample=simTime}updateUI(z);drawChart();drawResponse();heroWorld.render(now,z);labWorld.render(now,z);requestAnimationFrame(loop)}requestAnimationFrame(loop);
const reveal=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.animate([{opacity:0,transform:'translateY(25px)'},{opacity:1,transform:'none'}],{duration:800,easing:'cubic-bezier(.2,.8,.2,1)',fill:'both'});reveal.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.chapter-head,.story-card,.finding,.feedback,.caveat').forEach(e=>reveal.observe(e));
